[project]
name = "artifactory-navigator"
version = "v1.1.20260114"
description = "The Windows native Artifactory Navigator"
readme = "README.md"
requires-python = ">=3.13.0, <3.14"
dependencies = [
    "azure-cosmos>=4.9.0",
    "azure-storage-blob>=12.26.0",
    "cryptography>=45.0.5",
    "dohq-artifactory>=1.0.1",
    "keyring>=25.6.0",
    "msal>=1.34.0",
    "pip-system-certs>=5.2",
    "python-dotenv>=1.1.1",
    "pywin32>=311",
    "requests>=2.32.4",
    "wxpython>=4.2.3",
]

[dependency-groups]
dev = [
    "isort>=6.1.0",
    "pyinstaller>=6.16.0",
    "ruff>=0.14.0",
]
