[project]
name = "artifactory-navigator"
version = "0.1.20250814"
description = "The Windows native Artifactory Nagivator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-cosmos>=4.9.0",
    "azure-storage-blob>=12.26.0",
    "cryptography>=45.0.5",
    "dohq-artifactory>=1.0.1",
    "pip-system-certs>=5.2",
    "python-dotenv>=1.1.1",
    "pywin32>=311",
    "requests>=2.32.4",
    "wxpython>=4.2.3",
]
