name: LBS Artifactory Navigator

on:
  push:
    tags:
      - "v*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # --------------------------------------------------------------
      # 1️⃣ Checkout the Repository
      # --------------------------------------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v5

      # --------------------------------------------------------------
      # 2️⃣ Install UV (Python)
      # --------------------------------------------------------------
      - name: Set up UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      # --------------------------------------------------------------
      # 3️⃣ Install the Depentencies
      # --------------------------------------------------------------
      - name: Install Dependencies
        run: |
          uv sync
          uv pip install pyinstaller

      # --------------------------------------------------------------
      # 4️⃣ Generate the config file that contains the secrets
      # --------------------------------------------------------------
      - name: Generate .env
        run: |
          echo "APP_SECRET = `"${{ secrets.APP_SECRET }}`"" > .env
          echo "DST_AZURE_KEY = `"${{ secrets.DST_AZURE_KEY }}`"" >> .env
          echo "DST_STORAGE_ACCOUNT_NAME = `"${{ secrets.DST_STORAGE_ACCOUNT_NAME }}`"" >> .env
          echo "DST_STORAGE_ACCOUNT_CONTAINER = `"${{ secrets.DST_STORAGE_ACCOUNT_CONTAINER }}`"" >> .env
          echo "CONFIG_PATH = config.json" >> .env
          echo "VERSION = `"${{ github.ref_name }}`"" >> .env

      # --------------------------------------------------------------
      # 5️⃣ Build the Base Executable
      # --------------------------------------------------------------
      - name: Build Base Executable
        run: |
          uv run pyinstaller pyinstaller.spec
          dir dist

      # --------------------------------------------------------------
      # 6️⃣ Create Portable ZIP
      # --------------------------------------------------------------
      - name: Create Portable ZIP
        run: |
          if (-not (Test-Path dist_portable)) { New-Item -ItemType Directory -Path dist_portable }
          Compress-Archive -Path dist/* -DestinationPath dist_portable/Artifactory_Navigator_Portable.zip -Force
          dir dist_portable

      # --------------------------------------------------------------
      # 7️⃣ Install Inno Setup
      # --------------------------------------------------------------
      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      # --------------------------------------------------------------
      # 8️⃣ Build Installer
      # --------------------------------------------------------------
      - name: Build Installer
        run: |
          & "${env:ProgramFiles(x86)}\Inno Setup 6\iscc.exe" /DAppVersion="${{ github.ref_name }}" installer.iss
          dir Output

      # --------------------------------------------------------------
      # 9️⃣ Upload Build Artifacts
      # --------------------------------------------------------------
      - name: Upload Portable Executable
        uses: actions/upload-artifact@v4
        with:
          name: Portable-exe
          path: dist_portable/*

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: Installer
          path: Output/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------------------
      # 1️⃣ Download Build Artifacts
      # --------------------------------------------------------------
      - name: Download Portable Executable
        uses: actions/download-artifact@v4
        with:
          name: Portable-exe
          path: release_files

      - name: Download Installer
        uses: actions/download-artifact@v4
        with:
          name: Installer
          path: release_files

      # --------------------------------------------------------------
      # 2️⃣ Create Release
      # --------------------------------------------------------------
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release_files/*
